var details = {
	"endersgame": {
		"title": "Ender's Game",
		"author": "Orson Scott Card",
		"pubDate": "1/15/1985",
		"publisher": "Tor",
		"description": "The novel tells the story of a young boy, Ender Wiggin, who is sent to a training academy named Battle School, located in orbit above the Earth, built to train people to become soldiers that will one day battle against a vast alien race known as 'Buggers'",
		"rating": "4.31",
		"readingLevel": "10+",
		"pages": "324",
		"genre": "Science Fiction, Young Adult, Fantasy, Classics, Dystopia, War",
		"price": "$14.49",
		"related": "Speaker For the Dead, Ender's Shadows, Hunger Games",
		"awards": "Hugo Award for Best Novel (1986), Nebula Award for Best Novel (1985), Premio Ignotus for Mejor Cuento Extranjero (1994), Premi Ictineu for Millor novel·la traduïda (2014), Margaret A. Edwards Award (2008)",
		"isbn": "9781250773029"
	},
	"harrypotter": {
		"title": "Harry Potter and the Socerer's Stone",
		"author": "J.K Rowling",
		"pubDate": "6/30/1997",
		"publisher": "Bloomsbury Publishing",
		"description": "Adaptation of the first of J.K. Rowling's popular children's novels about Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwanted child to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies and help him discover the truth about his parents' mysterious deaths.",
		"rating": "4.47",
		"readingLevel": "6+",
		"pages": "223",
		"genre": "Fantasy, Fiction, Young Adult, Magic, Childrens, Classics",
		"price": "$19.95",
		"related": "Artemis Fowl, Lord Of The Rings, Game Of Thrones",
		"awards": "Mythopoeic Fantasy Award for Children's Literature (2008), British Book Award for Children's Book of the Year (1998), Kate Greenaway Medal Nominee (2017), Prijs van de Nederlandse Kinderjury for 6-9 jaar en 10-12 jaar (2002), American Booksellers Book Of The Year Award for Children (1999), Audie Award (2000), West Australian Young Readers' Book Award (WAYRBA) for Younger Readers (2000), South Carolina Book Award for Junior Book Award (2001), Grand Canyon Reader Award for Teen Book (2000), Charlotte Award (2000), Nene Award (2000), Massachusetts Children's Book Award (2000), Colorado Blue Spruce Young Adult Book Award (2001), Blue Hen Book Award for Chapter Book (2001), Nevada Young Readers' Award for Young Reader Category (2000), Golden Archer Award for Middle/Junior High (2000), Indian Paintbrush Book Award (2000), Hotze de Roosprijs (2002), Nestle` Smarties Book Prize for 9-11 years (1997), Eliot Rosewater Indiana High School Book Award (2001), Kinderboekwinkelprijs (1999), Parenting Book of the Year Award (1998), North East Teenage Book Award (1999), Specsavers National Book Award for Children's Book of the Year (1998), Washington State Sasquatch Award (2000), Literaturpreis der Jury der jungen Leser for Kinderbuch (1999), Carnegie Medal Nominee (1997), Rebecca Caudill Young Readers' Book Award (2001), Premi Protagonista Jove for Categoria 12-13 anys (2000)",
		"isbn": "9780590353403"
	},
	"agoodgirlsguide": {
		"title": "A Good Girl's Guide To Murder",
		"author": "Holly Jackson",
		"pubDate": "5/2/2019",
		"publisher": "Electric Monkey",
		"description": "The case is closed. Five years ago, schoolgirl Andie Bell was murdered by Sal Singh. The police know he did it. Everyone in town knows he did it. But having grown up in the same small town that was consumed by the murder, Pippa Fitz-Amobi isn't so sure. When she chooses the case as the topic for her final year project, she starts to uncover secrets that someone in town desperately wants to stay hidden. And if the real killer is still out there, how far will they go to keep Pip from the truth?",
		"rating": "4.35",
		"readingLevel": "13+",
		"pages": "443",
		"genre": "Mystery, Young Adult, Thriller, Mystery Thriller, Fiction, Contemporary, Crime",
		"price": "$12.88",
		"related": "Six Of Crows, They Wish They Were Us",
		"awards": "Kentucky Bluegrass Award for 9-12 (2022), Nominee for Translated Fiction (2022), Goodreads Choice Award Nominee for Young Adult Fiction (2020), British Book Awards Children's Book of the Year (2020)",
		"isbn": "9781984896391"
	},
	 "thegiver": {
		"title": "The Giver",
		"author": "Lois Lowery",
		"pubDate": "4/26/1993",
		"publisher": "Ember",
		"description": "The Giver is a morally driven and interesting story about a young boy called Jonas who lives in a society free of crime and sadness. At the age of 12, children are assigned their jobs, which they will train for and do for the rest of their lives. Everything is chosen; from your parents to your partner.",
		"rating": "4.12",
		"readingLevel": "12+",
		"pages": "208",
		"genre": "Young Adult, Fiction, Classics, Dystopia, Science Fiction, Fantasy, School",
		"price": "$15.59",
		"related": "Divergent, The Uglies",
		"awards": "Newbery Medal (1994), Mythopoeic Fantasy Award Nominee for Children's Literature (1994), Golden Duck Award for Young Adult (Hal Clement Award) (1994), Garden State Book Award for Teen Fiction Grades 6-8 (1996), Buckeye Children's Book Award for Grade 6-8 (1997), Grand Canyon Reader Award for Teen Book (1995), Maryland Black-Eyed Susan Book Award for Grade 6-9 (1995), Golden Sower Award for Young Adult (1995), Pennsylvania Young Readers' Choice Award for Grades 3-8 (1995), Soaring Eagle Book Award Nominee (1996), Pacific Northwest Library Association Young Reader's Choice Award for Senior (1996), Boston Globe-Horn Book Award Nominee for Fiction (1993), New Mexico Land of Enchantment Award (1997), Eliot Rosewater Indiana High School Book Award (1997), William Allen White Children's Book Award (1996), Wyoming Indian Paintbrush Nominee (1996), NSK Neustadt Prize for Children's Literature Nominee (2013), Oklahoma Sequoyah Award for YA (1996), Rebecca Caudill Young Readers' Book Award (1996), Hea Lasteraamat (2010), Premi Protagonista Jove for Categoria 13-14 anys (2016), Margaret A. Edwards Award (2007)",
		"isbn": "9780544336261"
	},
	"projecthailmary": {
		"title": "Project Hail Mary",
		"author": "Andy Weir",
		"pubDate": "5/4/2021",
		"publisher": "Ballantine Books",
		"description": "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
		"rating": "4.52",
		"readingLevel": "16+",
		"pages": "476",
		"genre": "Science Fiction, Fiction, Space, Fantasy, Adult, Thriller",
		"price": "$16.99",
		"related": "The Martian",
		"awards": "Hugo Award Nominee For Best Novel(2022), Audie Award for Best AudioBook and Science Fiction(2022), Goodreads Choice award for Science Fiction(2021), Green Mountain Book Award(2023)",
		"isbn": "9780593135228"
	},
	"themartian": {
		"title": "The Martian",
		"author": "Andy Weir",
		"pubDate": "9/27/2011",
		"publisher": "Crown",
		"description": "The Martian tells the story of Mark Watney, an astronaut on the Ares 3 mission to Mars. After a terrible storm almost destroys the ship and the base, the crew of his ship believe he is dead. Alone on the red planet, he has to survive until the next mission to Mars arrives.",
		"rating": "4.41",
		"readingLevel": "12+",
		"pages": "384",
		"genre": "Science Fiction, Fiction, Space, Adult, Thriller, Humor, Survival",
		"price": "$24.99",
		"related": "Ready Player One",
		"awards": "Kurd-Laßwitz-Preis for Bestes ausländisches Werk (2015), John W. Campbell Memorial Award Nominee for Best Science Fiction Novel (2015), ITW Thriller Award Nominee for Best First Novel (2015), Audie Award for Science Fiction (2015), ALA Alex Award (2015), Premio Ignotus for Mejor Novela Extranjera (Best Foreign Novel) (2015), 本屋大賞 Nominee for Translated Fiction (2015), Goodreads Choice Award for Science Fiction & Nominee for Debut Goodreads Author (2014) and Nominee for Best of the Best (2018), Green Mountain Book Award (2016), Seiun Award 星雲賞 for Best Foreign Novel (2015), RUSA CODES Reading List for Science Fiction (2015)",
		"isbn": "9780553418026"
	}
}